/// Flutter icons InventoryIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InventoryIcons
///      fonts:
///       - asset: fonts/InventoryIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InventoryIcons {
  InventoryIcons._();

  static const _kFontFam = 'InventoryIcons';
  static const String? _kFontPkg = null;

  static const IconData plus = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData in_out = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode_read = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData level_down_alt = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData level_up_alt = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_csv = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tachometer_alt_slowest = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layer_group = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_question = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
